### ISSUE TITLE
Name property does not include scope

### ISSUE THREAD

**Issue by lukehoban** [npm/read-package-tree#17]
The `name` property returned for Nodes does not appear to correctly report the scope-qualified name of the package.

For example, I see entries like this:

```
     Node {
       name: 'express',
       path: 'node_modules/@types/express',
       realpath: '/Users/luke/myapp/node_modules/@types/express',
       error: null,
       id: 1063,
       package: [Object],
       parent: [Circular],
       isLink: false,
       children: [] },
```

However, this package cannot be resolved with the name `express`, and should be reported as `@types/express`.

**Comment by isaacs** [comment]
Not sure when this got fixed, but it appears to no longer an issue in the latest release.  Thanks!
